In [1]:
import pandas as pd       
import seaborn as sb

df_ireland=pd.read_csv("ireland_production_index.csv")

df_ireland.head(5)

,Unnamed: 0,Value of Production Index in Building and Construction,Volume of Production Index in Building and Construction,Value of Production Index in Building and Construction (Seasonally Adjusted),Volume of Production Index in Building and Construction (Seasonally Adjusted)
0,"Source: Central Statistics Office, Ireland.",NaN,NaN,NaN,NaN
1,2000Q1,143.515,206.820,148.963,216.612
2,2000Q2,153.542,216.692,154.185,218.514
3,2000Q3,162.664,228.747,158.239,220.425
4,2000Q4,163.688,221.786,161.520,218.552